name: Post to HTTP Output
on:
  workflow_dispatch:
    inputs:
      cookie:
        type: string
        description: IntsPortal Auth Cookie
        required: true
      cookie-auth:
        type: boolean
        description: I will logout of the IntsPortal to terminate my session and reset my cookie/ token when this workflow is complete. I understand that failure to do this could result in unauthorised usage of my account.
      webhookid:
        type: choice
        description: Webhook ID
        options:
          -  1053298414277906532
        required: true

jobs:
  post-to-http-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute Test Script
        run: >
          COOKIE=${{ github.event.inputs.cookie }}
          WEBHOOK_ID=${{ github.event.inputs.webhookid }}
          WEBHOOK_TOKEN=${{ secrets.webhooktoken }}
          python3 webhook.py
      - name: Setup git config
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "<>"
      - name: Stage changed files
        run: git add interns.json
      - name: Commit changed files
        run: git commit -m "Update interns.json via Github Actions"
      - name: Push code to main
        run: git push origin main