name: Post to HTTP Output
on:
  workflow_dispatch:
    inputs:
      cookie:
        type: string
        description: IntsPortal Auth Cookie
        required: true
      platform:
        type: choice
        description: Output Platform
        options:
          -  Discord Webhook
      webhookid:
        type: string
        description: Webhook ID
        required: true
      webhooktoken:
        type: string
        description: Webhook Token
        required: true


jobs:
  post-to-http-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute Test Script
        run: >
          COOKIE=${{ github.event.inputs.cookie }}
          WEBHOOK_ID=${{ github.event.inputs.webhookid }}
          WEBHOOK_TOKEN=${{ github.event.inputs.webhooktoken }}
          python3 webhook.py
      - name: stage changed files
        run: git add interns.json
      - name: commit changed files
        run: git commit -m "Update interns.json via Github Actions"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main